---
title: "Using-Tidy-OHDSI-Recipies"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using-Tidy-OHDSI-Recipies}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyOhdsiRecipies)
library(fs)
library(dplyr)
library(CDMConnector)
library(purrr)
```


## Create "study" directory

```{r}
studyDir <- fs::dir_create(path = 'tmp')
```
### Create "target" and other cohorts
```{r}
target <- returnTestDonorCohort()
## Collect cs to build other cohorts
conceptSets <- collectCaprCsFromCohort(target)
print(names(conceptSets))
```
## Create other cohorts from concept sets

```{r}
csBasedCohorts <- map(conceptSets, ~ createCaprConceptSetCohort(
  .x,
  # all events
  limit = 'all',
  end = 'fixed_exit',
  endArgs = list(
    # exit after 1 day after start
    index = c("startDate"), offsetDays = 1)
))
names(csBasedCohorts)
```

## Gather all the cohorts and create generation set from cohorts

```{r}
# option 1 create generation set from list cohorts
cohortsToCreate <- createCohortsToCreate(cohorts = csBasedCohorts)
```
## Write cohorts to study directory
```{r}
grid <- tibble(
  cohort = csBasedCohorts, 
  cohortName = names(csBasedCohorts), 
  saveLocation= studyDir
)
pwalk(grid, writeListCohort)
```

## Create cohortToCreate from jsons 
```{r}
generationSet <- createCohortsToCreate(
  path = studyDir
)
fs::dir_delete(studyDir)
head(generationSet)
```
