test_that("Mapping and Gathering", {
  cdm <- tidyOhdsiRecipies::tidyCdmMock()
  conceptIds <- tidyOhdsiRecipies::conceptIdsFromSources(cdm, c("63020004901"), c("NDC"))
  testthat::expect_equal(conceptIds, 45176377)
  standardConcepts <- tidyOhdsiRecipies::standardFromSourceConceptIds(cdm, conceptIds)
  testthat::expect_equal(standardConcepts, 19102219)
  icd10_with_dot <- tidyOhdsiRecipies::addDot("A001")
  testthat::expect_equal(icd10_with_dot, "A00.1")
  testthat::expect_equal(tidyOhdsiRecipies::addDot("A00"), "A00")
  r <- tidyOhdsiRecipies::getDescendants(1124300, CDMConnector::cdmCon(cdm), "main")
  testthat::expect_equal(r, c(21164797, 1124300))
  CDMConnector::cdmDisconnect(cdm)
})
